/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ober_stat1 (void);
GtkWidget* create_obser_stat2 (void);
GtkWidget* create_obser_stat3 (void);
GtkWidget* create_obser_stat4 (void);
